const productOptions = [
    'Candles - Small',
    'Candles - Large',
    'Candles - X-Large',
    'Candles - Deluxe',
    'Candy - Mini',
    'Candy - Small',
    'Candy - Medium',
    'Candy - Large',
    'Candy - X-Large',
    'Candy - Grand',
    'Cocktail Mixers - Medium',
    'Cocktail Mixers - Large',
    'Cocktail Mixers - X-Large',
    'Cocktail Mixers - Deluxe',
    'Cocktail Mixers - Grand',
    'Cocktails - Small',
    'Cocktails - Medium',
    'Cocktails - Large',
    'Cocktails - X-Large',
    'Cocktails - Deluxe',
    'Cocktails - Grand',
    'Coffee & Tea - Mini',
    'Coffee & Tea - Small',
    'Coffee & Tea - Medium',
    'Coffee & Tea - Large',
    'Coffee & Tea - X-Large',
    'Coffee & Tea - Deluxe',
    'Coffee & Tea - Grand',
    'Cookies - Mini',
    'Cookies - Small',
    'Cookies - Medium',
    'Cookies - Large',
    'Cookies - X-Large',
    'Cookies - Deluxe',
    'Cookies - Grand',
    'Custom Select - Mini',
    'Custom Select - Small',
    'Custom Select - Medium',
    'Custom Select - Large',
    'Custom Select - X-Large',
    'Custom Select - Deluxe',
    'Custom Select - Grand',
    'Dog Treats - Mini',
    'Dog Treats - Small',
    'Dog Treats - Medium',
    'Dog Treats - Large',
    'Dog Treats - X-Large',
    'Dog Treats - Grand',
    'Drinks - Select-Mini',
    'Drinks - Select-Small',
    'Drinks - Select-Medium',
    'Drinks - Select-Large',
    'Drinks - Select-X-Large',
    'Drinks - Select-Deluxe',
    'Drinks - Select-Grand',
    'Flowers - Classic',
    'Flowers - Deluxe',
    'Popcorn - Mini',
    'Popcorn - Small',
    'Popcorn - Medium',
    'Popcorn - Large',
    'Popcorn - X-Large',
    'Select - Mini',
    'Select - Small',
    'Select - Medium',
    'Select - Large',
    'Select - X-Large',
    'Select - Deluxe',
    'Select - Grand',
    'Snacks - Grand',
    'Snacks - Large',
    'Snacks - Medium',
    'Snacks - Mini',
    'Snacks - Small',
    'Snacks - X-Large',
    'Treats Select - Mini',
    'Treats Select - Small',
    'Treats Select - Medium',
    'Treats Select - Large',
    'Treats Select - X-Large',
    'Treats Select - Grand',
    'Wine - Small',
    'Wine - Medium',
    'Wine - Large',
    'Wine - X-Large',
    'Wine - Deluxe',
    'Wine - Grand',
    'Wine Tastings - Small',
    'Wine Tastings - Medium',
    'Wine Tastings - Large',
    'Wine Tastings - X-Large',
    'Wine Tastings - Deluxe',
    'Wine Tastings - Grand'
]

const productSeletcion = [
    'Candles - Small',
    'Candles - Large',
    'Candles - X-Large',
    'Candles - Deluxe'
]

let quantity = 0;
let size = productOptions.length;
console.log(size)

for (let index = 0; index < size; index++) {
    if (productSeletcion[index] === productOptions[index]) {
        quantity++;
    }
}

console.log(quantity);